Implementa notificación para administradores y gestores con cuenta de…
Wave-dev-UV/Android-Renacer pull request #30
Opened 2024-11-01 08:05 UTC by AlejoZA

Se he implemento la funcionalidad para notificar a los usuarios con rol de Administrador o Gestor cuando tienen personas pendientes en la lista. 
La notificación se programa con un intervalo  de 12 horas.

Componentes Añadidos:
PendienteNotificationWorker.kt: Worker que maneja el envío de notificaciones y verifica el rol.

Componentes Modificados:
MainActivity.kt: Se añadió la verificación del rol y programación de la notificación.
UserRepositorio.kt: Método añadido para obtener el conteo de usuarios pendientes.
UserViewModel.kt: Método añadido para actualizar el número de usuarios pendientes.

Permisos:
POST_NOTIFICATIONS: Permiso solicitado en AndroidManifest.xml para enviar notificaciones en Android 13 o superior.

2024-11-01 14:07 UTC, Criser2013 requested changes
Hay algunas cosas por cambiar:
- La notificación se debe planificar al cerrar la aplicación, se está mostrando el tiempo estipulado (12 horas) después de abrir la app. el resto está correcto, bájale el tiempo a `8 horas`.
- Se te está olvidando borrar el rol del archivo `sharedPreferences`, si inicio sesión como administrador, se planifica la notificación. Pero si luego abro la app. (sin haber iniciado sesión) se sigue planificando la notificación.
- Cambia el mensaje de la notificación a: `Tienes personas pendientes por llamar.`.
  
El resto está perfecto.

2024-11-07 20:41 UTC, Criser2013 requested changes
Cuando se vacía la lista y se cierra la app, se sigue enviando la notificación (independientemente si se hace en la ventana de listar o la `lista por llamar`).
  
![image](https://github.com/user-attachments/assets/490555e6-e963-4aac-b869-4873d587e3ad)

2024-11-08 07:38 UTC, AlejoZA commented
se implementa la validación para no programar la notificación si la lista de pendientes es 0

2024-11-08 17:06 UTC, Criser2013 approved these changes
Bien hecho.

2024-11-08 17:08 UTC, merged