Gpuv 15 grupos
Wave-dev-UV/Android-Renacer pull request #33
Opened 2024-11-04 14:45 UTC by paulrojasg

# Grupos 
## H.U.
**H.U. - 15:** La funcionalidad de grupos o filtros predefinidos permite guardar configuraciones de múltiples filtros como una sola instancia para que el grupo pueda ser utilizado para llamar a todos los usuarios que son seleccionados por los filtros.

  

## Componenentes.
### Componentes añadidos:
- Group (model)
- GrupoRepositorio
- GroupAdapter
- GroupViewModel

### Componentes modificados
- ListarFragment
- PendingFragment
- ModalBottomSheet
- FragmentPlantillaMensajes
- SheetFiltros
- nav_graph
- strings.xml

2024-11-05 14:00 UTC, Criser2013 requested changes
El desarrollo de la funcionalidad está correcto, todo acorde a como se definió la H.U. Encontré 1 error a nivel de interfaz que hay que corregir:

- La ventana de enviar SMS no es scrolleable, cuando se gira el celular, el btón de enviar y la parte de seleccionar plantillas se vuelve inaccesible.

2024-11-06 08:28 UTC, paulrojasg commented
> El desarrollo de la funcionalidad está correcto, todo acorde a como se definió la H.U. Encontré 1 error a nivel de interfaz que hay que corregir:
> 
>     * La ventana de enviar SMS no es scrolleable, cuando se gira el celular, el btón de enviar y la parte de seleccionar plantillas se vuelve inaccesible.

Solucionado problema de scroll cuando el celular está en modo landscape en el fragmento de enviar sms

2024-11-07 20:47 UTC, Criser2013 approved these changes

2024-11-07 20:48 UTC, Criser2013 commented
Bien hecho.

2024-11-08 05:41 UTC, AlejoZA approved these changes

2024-11-08 05:42 UTC, AlejoZA requested changes
solo faltaría solucionar los conflictos

2024-11-08 09:17 UTC, paulrojasg commented
> solo faltaría solucionar los conflictos

Ya solucioné los conflictos.

2024-11-08 09:19 UTC, AlejoZA approved these changes

2024-11-08 09:19 UTC, merged